apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: github-mcp-backend
spec:
  type: MCP
  mcp:
    targets:
    - name: mcp-target
      static:
        host: api.githubcopilot.com
        port: 443
        path: /mcp/
---
apiVersion: gateway.networking.k8s.io/v1alpha3	
kind: BackendTLSPolicy
metadata:
  name: github-mcp-backend-tls
  namespace: default
spec:
  targetRefs:
    - name: github-mcp-backend
      kind: Backend
      group: gateway.kgateway.dev
  validation:
    hostname: api.githubcopilot.com
    wellKnownCACertificates: System
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-github
spec:
  parentRefs:
  - name: agentgateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp-github
      filters:
        - type: CORS
          cors:
            allowHeaders:
              - "*"               
            allowMethods:            
              - "*"              
            allowOrigins:
              - "http://localhost:15000"
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set: 
              - name: Authorization
                value: "Bearer github_pat_blah_blah_blah"
      backendRefs:
      - name: github-mcp-backend
        group: gateway.kgateway.dev
        kind: Backend  